/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Char(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/tesModel-V3.gltf')
  const { actions } = useAnimations(animations, group)

  // Log the animations to the console
  console.log(animations)

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Icosphere"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere.geometry}
          material={nodes.Icosphere.material}
          scale={0}
        />
        <group name="Armature">
          <group name="Body">
            <skinnedMesh
              name="Body_(merged)"
              geometry={nodes['Body_(merged)'].geometry}
              material={materials['N00_000_00_Body_00_SKIN (Instance)']}
              skeleton={nodes['Body_(merged)'].skeleton}
            />
            <skinnedMesh
              name="Body_(merged)_1"
              geometry={nodes['Body_(merged)_1'].geometry}
              material={materials['N00_007_01_Tops_01_CLOTH_01 (Instance)']}
              skeleton={nodes['Body_(merged)_1'].skeleton}
            />
            <skinnedMesh
              name="Body_(merged)_2"
              geometry={nodes['Body_(merged)_2'].geometry}
              material={materials['N00_001_02_Bottoms_01_CLOTH (Instance)']}
              skeleton={nodes['Body_(merged)_2'].skeleton}
            />
            <skinnedMesh
              name="Body_(merged)_3"
              geometry={nodes['Body_(merged)_3'].geometry}
              material={materials['N00_006_01_Shoes_01_CLOTH (Instance)']}
              skeleton={nodes['Body_(merged)_3'].skeleton}
            />
            <skinnedMesh
              name="Body_(merged)_4"
              geometry={nodes['Body_(merged)_4'].geometry}
              material={materials['N00_007_01_Tops_01_CLOTH_02 (Instance)']}
              skeleton={nodes['Body_(merged)_4'].skeleton}
            />
            <skinnedMesh
              name="Body_(merged)_5"
              geometry={nodes['Body_(merged)_5'].geometry}
              material={materials['N00_007_02_Tops_01_CLOTH (Instance)']}
              skeleton={nodes['Body_(merged)_5'].skeleton}
            />
            <skinnedMesh
              name="Body_(merged)_6"
              geometry={nodes['Body_(merged)_6'].geometry}
              material={materials['N00_007_02_Accessory_Tie_01_CLOTH (Instance)']}
              skeleton={nodes['Body_(merged)_6'].skeleton}
            />
            <skinnedMesh
              name="Body_(merged)_7"
              geometry={nodes['Body_(merged)_7'].geometry}
              material={materials['N00_000_00_HairBack_00_HAIR (Instance)']}
              skeleton={nodes['Body_(merged)_7'].skeleton}
            />
          </group>
          <group name="Face">
            <skinnedMesh
              name="Face_(merged)(Clone)"
              geometry={nodes['Face_(merged)(Clone)'].geometry}
              material={materials['N00_000_00_FaceMouth_00_FACE (Instance)']}
              skeleton={nodes['Face_(merged)(Clone)'].skeleton}
              morphTargetDictionary={nodes['Face_(merged)(Clone)'].morphTargetDictionary}
              morphTargetInfluences={nodes['Face_(merged)(Clone)'].morphTargetInfluences}
            />
            <skinnedMesh
              name="Face_(merged)(Clone)_1"
              geometry={nodes['Face_(merged)(Clone)_1'].geometry}
              material={materials['N00_000_00_EyeIris_00_EYE (Instance)']}
              skeleton={nodes['Face_(merged)(Clone)_1'].skeleton}
              morphTargetDictionary={nodes['Face_(merged)(Clone)_1'].morphTargetDictionary}
              morphTargetInfluences={nodes['Face_(merged)(Clone)_1'].morphTargetInfluences}
            />
            <skinnedMesh
              name="Face_(merged)(Clone)_2"
              geometry={nodes['Face_(merged)(Clone)_2'].geometry}
              material={materials['N00_000_00_EyeHighlight_00_EYE (Instance)']}
              skeleton={nodes['Face_(merged)(Clone)_2'].skeleton}
              morphTargetDictionary={nodes['Face_(merged)(Clone)_2'].morphTargetDictionary}
              morphTargetInfluences={nodes['Face_(merged)(Clone)_2'].morphTargetInfluences}
            />
            <skinnedMesh
              name="Face_(merged)(Clone)_3"
              geometry={nodes['Face_(merged)(Clone)_3'].geometry}
              material={materials['N00_000_00_Face_00_SKIN (Instance)']}
              skeleton={nodes['Face_(merged)(Clone)_3'].skeleton}
              morphTargetDictionary={nodes['Face_(merged)(Clone)_3'].morphTargetDictionary}
              morphTargetInfluences={nodes['Face_(merged)(Clone)_3'].morphTargetInfluences}
            />
            <skinnedMesh
              name="Face_(merged)(Clone)_4"
              geometry={nodes['Face_(merged)(Clone)_4'].geometry}
              material={materials['N00_000_00_EyeWhite_00_EYE (Instance)']}
              skeleton={nodes['Face_(merged)(Clone)_4'].skeleton}
              morphTargetDictionary={nodes['Face_(merged)(Clone)_4'].morphTargetDictionary}
              morphTargetInfluences={nodes['Face_(merged)(Clone)_4'].morphTargetInfluences}
            />
            <skinnedMesh
              name="Face_(merged)(Clone)_5"
              geometry={nodes['Face_(merged)(Clone)_5'].geometry}
              material={materials['N00_000_00_FaceBrow_00_FACE (Instance)']}
              skeleton={nodes['Face_(merged)(Clone)_5'].skeleton}
              morphTargetDictionary={nodes['Face_(merged)(Clone)_5'].morphTargetDictionary}
              morphTargetInfluences={nodes['Face_(merged)(Clone)_5'].morphTargetInfluences}
            />
            <skinnedMesh
              name="Face_(merged)(Clone)_6"
              geometry={nodes['Face_(merged)(Clone)_6'].geometry}
              material={materials['N00_000_00_FaceEyeline_00_FACE (Instance)']}
              skeleton={nodes['Face_(merged)(Clone)_6'].skeleton}
              morphTargetDictionary={nodes['Face_(merged)(Clone)_6'].morphTargetDictionary}
              morphTargetInfluences={nodes['Face_(merged)(Clone)_6'].morphTargetInfluences}
            />
          </group>
          <skinnedMesh
            name="Hair"
            geometry={nodes.Hair.geometry}
            material={materials['N00_000_Hair_00_HAIR (Instance)']}
            skeleton={nodes.Hair.skeleton}
          />
          <primitive object={nodes.Root} />
          <primitive object={nodes.Ctrl_Master} />
          <primitive object={nodes.Ctrl_ArmPole_IK_Left} />
          <primitive object={nodes.Ctrl_Hand_IK_Left} />
          <primitive object={nodes.Ctrl_ArmPole_IK_Right} />
          <primitive object={nodes.Ctrl_Hand_IK_Right} />
          <primitive object={nodes.Ctrl_Foot_IK_Left} />
          <primitive object={nodes.Ctrl_LegPole_IK_Left} />
          <primitive object={nodes.Ctrl_Foot_IK_Right} />
          <primitive object={nodes.Ctrl_LegPole_IK_Right} />
        </group>
        <group name="cs_grp" scale={0}>
          <lineSegments
            name="cs_arm_fk"
            geometry={nodes.cs_arm_fk.geometry}
            material={nodes.cs_arm_fk.material}
            scale={0}
          />
          <lineSegments
            name="cs_calf_fk"
            geometry={nodes.cs_calf_fk.geometry}
            material={nodes.cs_calf_fk.material}
            scale={0}
          />
          <lineSegments
            name="cs_circle"
            geometry={nodes.cs_circle.geometry}
            material={nodes.cs_circle.material}
            scale={0}
          />
          <lineSegments
            name="cs_circle001"
            geometry={nodes.cs_circle001.geometry}
            material={nodes.cs_circle001.material}
            scale={0}
          />
          <lineSegments
            name="cs_circle_025"
            geometry={nodes.cs_circle_025.geometry}
            material={nodes.cs_circle_025.material}
            scale={0}
          />
          <lineSegments
            name="cs_foot"
            geometry={nodes.cs_foot.geometry}
            material={nodes.cs_foot.material}
            scale={0}
          />
          <lineSegments
            name="cs_foot001"
            geometry={nodes.cs_foot001.geometry}
            material={nodes.cs_foot001.material}
            scale={0}
          />
          <lineSegments
            name="cs_foot002"
            geometry={nodes.cs_foot002.geometry}
            material={nodes.cs_foot002.material}
            scale={0}
          />
          <lineSegments
            name="cs_foot_01"
            geometry={nodes.cs_foot_01.geometry}
            material={nodes.cs_foot_01.material}
            scale={0}
          />
          <lineSegments
            name="cs_foot_roll"
            geometry={nodes.cs_foot_roll.geometry}
            material={nodes.cs_foot_roll.material}
            scale={0}
          />
          <lineSegments
            name="cs_forearm_fk"
            geometry={nodes.cs_forearm_fk.geometry}
            material={nodes.cs_forearm_fk.material}
            scale={0}
          />
          <lineSegments
            name="cs_hand"
            geometry={nodes.cs_hand.geometry}
            material={nodes.cs_hand.material}
            scale={0}
          />
          <lineSegments
            name="cs_head"
            geometry={nodes.cs_head.geometry}
            material={nodes.cs_head.material}
            scale={0}
          />
          <lineSegments
            name="cs_hips"
            geometry={nodes.cs_hips.geometry}
            material={nodes.cs_hips.material}
            scale={0}
          />
          <lineSegments
            name="cs_master"
            geometry={nodes.cs_master.geometry}
            material={nodes.cs_master.material}
            scale={0}
          />
          <lineSegments
            name="cs_neck"
            geometry={nodes.cs_neck.geometry}
            material={nodes.cs_neck.material}
            scale={0}
          />
          <lineSegments
            name="cs_shoulder_left"
            geometry={nodes.cs_shoulder_left.geometry}
            material={nodes.cs_shoulder_left.material}
            scale={0}
          />
          <lineSegments
            name="cs_shoulder_right"
            geometry={nodes.cs_shoulder_right.geometry}
            material={nodes.cs_shoulder_right.material}
            scale={0}
          />
          <lineSegments
            name="cs_sphere"
            geometry={nodes.cs_sphere.geometry}
            material={nodes.cs_sphere.material}
            scale={0}
          />
          <lineSegments
            name="cs_sphere_012"
            geometry={nodes.cs_sphere_012.geometry}
            material={nodes.cs_sphere_012.material}
            scale={0}
          />
          <lineSegments
            name="cs_square"
            geometry={nodes.cs_square.geometry}
            material={nodes.cs_square.material}
            scale={0}
          />
          <lineSegments
            name="cs_square_2"
            geometry={nodes.cs_square_2.geometry}
            material={nodes.cs_square_2.material}
            scale={0}
          />
          <lineSegments
            name="cs_thigh_fk"
            geometry={nodes.cs_thigh_fk.geometry}
            material={nodes.cs_thigh_fk.material}
            scale={0}
          />
          <lineSegments
            name="cs_toe"
            geometry={nodes.cs_toe.geometry}
            material={nodes.cs_toe.material}
            scale={0}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/tesModel-V3.gltf')

export default Char;
